version: '3'
services:
  app1:
    container_name: app1
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    network_mode: host
    volumes:
      - /etc/ssl/app/cert.pem:/etc/ssl/app/cert.pem
      - /etc/ssl/app/cert.key:/etc/ssl/app/cert.key

  app2:
    container_name: app2
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    network_mode: host

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80
    network_mode: host
